import type { Metadata } from "next";
import "./globals.css";
import { Questrial } from "next/font/google";
import { NavMenu } from "@/components/shared/Navbar";
import { Footer } from "@/components/shared/Footer/Footer";

const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {

  return (
    <html lang="en">
      <body className={`${questrial.variable} antialiased`}>
        <NavMenu />
        <main className="text-primary">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}